# Le fichier docker-compose.yml a pour objectif de définir et orchestrer l'ensemble
# de ton environnement d'exécution avec Docker.

# Dans ton projet MacroBus (Data Engineering), il permet de créer automatiquement
# l'infrastructure nécessaire pour exécuter ton pipeline ETL avec Airflow + PostgreSQL
# sans avoir à installer et configurer chaque composant manuellement.

#version: "3.9" # Version de Docker Compose utilisée
# Pas besoin de spécifier la version, Docker Compose utilise la dernière par défaut

# Un service représente un composant de ton application qui sera exécuté dans un conteneur Docker.

services:
  # =========================
  # SERVICE POSTGRESQL UNIQUE
  # =========================

  # Un service est un service est simplement un composant de ton application qui tourne dans un conteneur.
  # Tout simplement un service est un conteneur Docker qui tourne en arrière-plan et qui fournit une fonctionnalité spécifique à ton application.

  # Service 1: PostgreSQL (base de données relationnelle)
  airflow_db:
    image: postgres:15 # Image officielle PostgreSQL, Une image est un modèle permettant de créer un conteneur.
    container_name: airflow_db # Nom du conteneur

    # ✅ Chargement des variables depuis .env, Docker charge les informations depuis le fichier .env.
    env_file:
      - .env

    ports:
      - "5433:5432" # port local 5433 → conteneur 5432 (évite conflit avec PostgreSQL local)
      # le port qui va permettre de se à connecter Power BI ou à PostgreSQL localement est 5433, mais à l'intérieur du conteneur, Airflow se connectera à 5432

    volumes:
      - airflow_data:/var/lib/postgresql/data # persistance des données de la base postgres

  # =========================
  # SERVICE AIRFLOW (WEB + SCHEDULER)
  # =========================
  airflow:
    image: apache/airflow:2.9.2 # Image officielle Airflow
    container_name: airflow

    depends_on:
      - airflow_db # Airflow dépend de la base PostgreSQL

    restart: always # redémarrage automatique si crash c'est à dire que si le conteneur Airflow plante, Docker va automatiquement le redémarrer.

    # ✅ Chargement des variables depuis .env
    env_file:
      - .env

    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor # exécution locale (pas de Celery)
      AIRFLOW__CORE__LOAD_EXAMPLES: "false" # désactive les DAGs exemples

      # Connexion à la base postgres avec les variables .env
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}

      # Permet à Python de trouver tes scripts ETL et DAGs
      PYTHONPATH: /opt/airflow:/opt/airflow/ETL

    volumes:
      - ./DAG:/opt/airflow/dags # DAGs
      - ./ETL:/opt/airflow/ETL # code ETL (Bronze/Silver/Gold)
      - ./data:/opt/airflow/data # fichiers CSV ou datasets

    ports:
      - "8080:8080" # interface web Airflow accessible sur localhost:8080

    command: >
      bash -c "
      airflow db migrate &&             # initialise/migre la base postgres

      airflow users create              # crée un utilisateur admin pour l'UI
        --username admin
        --password admin
        --firstname Franck
        --lastname Batty
        --role Admin
        --email admin@example.com || true &&

      airflow scheduler & airflow webserver  # lance scheduler + UI
      "

# =========================
# VOLUMES PERSISTANTS
# =========================
volumes:
  airflow_data: # sauvegarde des données PostgreSQL
